---
title: "Untitled"
output: html_document
date: "2023-01-08"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
cat("\014")
rm(list = ls(all = TRUE))
```

```{r}
load("C:/Users/wjyjy/Documents/TDA/Mandibular Molars/alignment_ECT/Mirza.RData")
Mirza = data
load("C:/Users/wjyjy/Documents/TDA/Mandibular Molars/alignment_ECT/Saimiri.RData")
Saimiri = data
```

```{r}
number_iterations =6
number_directions = 2918
grid_length = 200
T=3
```

```{r}
ECT_1_list=list()
for (i in 1:number_iterations) {
  ECT_1_list[[i]]=t(Mirza[[i]])
}

ECT_2_list=list()
for (i in 1:number_iterations) {
  ECT_2_list[[i]]=t(Saimiri[[i]])
}
```


```{r}
    t_grid=seq(from=0, to=T, length.out = grid_length)
    SECT_1_list=list()
    ECT=matrix(NA, ncol = number_directions, nrow = grid_length)
    for (iterations in 1:number_iterations) {
    
    
    ECT_2D_results=ECT_1_list[[iterations]]
    PECT=matrix(NA, ncol = number_directions, nrow = grid_length)
    for (i in 1:dim(ECT_2D_results)[2]) {
      PECT[,i]=(T/grid_length)*cumsum(ECT_2D_results[,i])
    }
    
    PECT_2D_results=PECT
    SECT=matrix(NA, ncol = number_directions, nrow = grid_length)
    for (i in 1:dim(PECT_2D_results)[2]) {
      SECT[,i]=PECT_2D_results[,i]-(PECT_2D_results[dim(PECT_2D_results)[1],i]/T)*t_grid
    }
    
    SECT_1_list[[iterations]]=SECT
    }
    set.seed(193)
    t_grid=seq(from=0, to=T, length.out = grid_length)
    SECT_2_list=list()
    ECT=matrix(NA, ncol = number_directions, nrow = grid_length)
    for (iterations in 1:number_iterations) {
    
    
    ECT_2D_results=ECT_2_list[[iterations]]
    PECT=matrix(NA, ncol = number_directions, nrow = grid_length)
    for (i in 1:dim(ECT_2D_results)[2]) {
      PECT[,i]=(T/grid_length)*cumsum(ECT_2D_results[,i])
    }
    
    PECT_2D_results=PECT
    SECT=matrix(NA, ncol = number_directions, nrow = grid_length)
    for (i in 1:dim(PECT_2D_results)[2]) {
      SECT[,i]=PECT_2D_results[,i]-(PECT_2D_results[dim(PECT_2D_results)[1],i]/T)*t_grid
    }
    
    SECT_2_list[[iterations]]=SECT
  }

 SECT_both_list= c(SECT_1_list, SECT_2_list)
 
euclidean <- function(a, b) (sqrt(sum((a - b)^2)))
F_statistic_original = 0
F_matrix=matrix(0, ncol = number_iterations*2, nrow = number_iterations*2)
dir_sup=matrix(0, ncol = number_directions, nrow = 1)
for (i in 1:(number_iterations*2)) {
  SECTk = SECT_both_list[[i]]
  for (j in 1:(number_iterations*2)) {
    SECTl = SECT_both_list[[j]]
     for (m in 1:number_directions) {
      dir_sup[1,m]=euclidean(SECTk[,m],SECTl[,m])
     }
    F_matrix[i,j]=max(dir_sup)
  }}
```


```{r}
for (i in 1:number_iterations) {
for (j in 1:number_iterations) { F_statistic_original = F_statistic_original + F_matrix[i,j] +　F_matrix[i+number_iterations,j+number_iterations]}}
  
  ###############################################################
  ### Permutation test
  ###############################################################
  
  number_permutations=1000
  ECT_1_list=list()
  ECT_2_list=list()
  F_statistic_seq=vector()
  for (perm in 1:number_permutations) {
    
    all_indices=1:(2*number_iterations)
    sampled_indices=sample(all_indices, size=number_iterations, replace = FALSE)
    unsampled_indices=all_indices[-sampled_indices]
#    for (i in 1:number_iterations) {
#      ECT_1_list[[i]]=ECT_both_list[[sampled_indices[i]]]
#      ECT_2_list[[i]]=ECT_both_list[[unsampled_indices[i]]]
#    }
    
F=0   
for (i in 1:number_iterations) {
for (j in 1:number_iterations) { F = F + F_matrix[sampled_indices[i],sampled_indices[j]] +　F_matrix[unsampled_indices[i],unsampled_indices[j]]}}
F_statistic_seq[perm]=F
 }

decreasing_F_stat=sort(F_statistic_seq,decreasing=TRUE)
p_value=1-(which(decreasing_F_stat<F)[1])/1000
p_value

```



